config/routes.rb
Rails.application.routes.draw do


	#管理者以外のログインアウト後
	root to: 'tour_guide/home#about'


	get 'tour_guide/window' => 'tour_guide/home#window', as: 'home_window'
	get 'home/introduction' => 'tour_guide/home#introduction', as: 'introduction'



	  devise_for :admins, controllers: {
	  sessions:      'admins/sessions',
	  passwords:     'admins/passwords',
	  registrations: 'admins/registrations'
	}

	  devise_for :guides, controllers: {
	  sessions:      'guides/sessions',
	  passwords:     'guides/passwords',
	  registrations: 'guides/registrations'
	}
	devise_scope :guide do
	    post "guides/sign_in_with_guest" => "guides/sessions#guide_guest", as: 'guests_guide'
	end

	devise_for :tourists, controllers: {
	  sessions:      'guides/sessions',
	  passwords:     'guides/passwords',
	  registrations: 'guides/registrations'
	}
	devise_scope :tourist do
	    post "tourists/sign_in_with_guest" => "tourists/sessions#tourist_guest", as: 'guests_tourist'
	end



	# 管理者
	namespace :admin do
	    get 'home/top'
	    get 'search/search'
	    get 'orders/today' => 'orders#today', as: 'orders_today'
	    get 'contacts/thanks' => 'contacts#thanks', as: 'contact_thanks'
	    resources :contacts, only: [:index, :new, :edit, :update, :create]
	    resources :comments, only: [:destroy]
	    resources :cities, only: [:index, :create, :edit, :update, :destroy]
	    resources :rooms, only: [:show, :index, :destroy]
	    resources :genres, only: [:index, :create, :edit, :update, :destroy]
	    resources :guides, only: [:show, :index, :update, :destroy,]
	    resources :tourists, only: [:show, :index, :update, :destroy]
	    resources :orders, only: [:show, :index]
	    resources :tours, only: [:show, :index, :update]
	end



	# ツアーとツアーガイド
	namespace :tour_guide do
	    get 'top' => 'home#top'
		get 'guides/thanks' => 'guides#thanks', as: 'guide_thanks'


	    resources :guides, only: [:show, :edit, :update, :destroy] do
	    	get 'tourists/delete' => 'guides#delete', as: 'guide_delete'
	    	get 'orders/new_order' => 'orders#new_order', as: 'new_order'
	    	get 'orders/around_touring' => 'ordersaround_touring', as: 'around_touring'
	    	get 'orders/finished_tour' => 'orders#finished_tour', as: 'finished_tour'
	    	get 'orders/reviewed_tour' => 'orders#reviewed_tour', as: 'reviewed_tour'
	    	resources :notifications, only: [:index]
	    	resources :orders, only: [:index, :update]
	    	resources :rooms, only: [:show, :index, :create] do
	    		resources :messages, only: [:create]
	    	end
	    	resources :tours do
	    		resource :photos, only: [:new, :create]
	    	end
	    end
	end




	# 観光客
	namespace :tourist do
		get 'search/search'
		get 'orders/thanks' => 'orders#thanks', as: 'orders_thanks'
		get 'tourists/thanks' => 'tourists#thanks', as: 'tourist_thanks'

		resources :tourists, only: [:show, :edit, :update, :destroy] do
			get 'tours/bookmarks' => 'book_marks#index', as: 'book_mark'
			get 'tours/my_account' => 'tourist#my_account', as: 'my_account'
			get 'orders/confirm' => 'orders#confirm', as: 'orders_confirm'
			get 'tourists/delete' => 'tourists#delete', as: 'tourist_delete'
			resources :orders, only: [:show, :index, :new, :create, :destroy]
			resources :chat_notices, only: [:index]
			resources :rooms, only: [:show, :index, :create] do
		    	resources :messages, only: [:create]
		    end
		    resources :tours, only: [:show, :index] do
		    	resources :comments, only: [:create]
				resource :book_marks, only: [:create, :destroy]
			end
		end

	end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/admin/tourists_controller.rb
class Admin::TouristsController < ApplicationController

	before_action :authenticate_admin!


  def index
  	@tourists = Tourist.all.with_deleted
  end

  def show
  	@tourist = Tourist.with_deleted.find(params[:id])
    @orders = @tourist.orders
  end

  def update
    @tourist = Tourist.with_deleted.find(params[:id])
      if @tourist.update(tourist_params)
        if tourist_params[:deleted_at].to_i == 0
          flash[:notice] = "情報を更新しました"
           @tourist.restore
           redirect_to admin_tourist_path(@tourist)
        else
          flash[:notice] = "情報を更新しました"
           @tourist.destroy
           redirect_to admin_tourist_path(@tourist)
        end
      else
        flash[:notice] = "情報の更新に失敗しました"
         render 'edit'
      end
  end

  private
  def tourist_params
    params.require(:tourist).permit(:deleted_at)
  end

end

app/controllers/tourist/book_marks_controller.rb
class Tourist::BookMarksController < ApplicationController

    before_action :authenticate_tourist!
    before_action :correct_tourist, only: [:create, :destroy, :index]


    def index
        @book_marks = current_tourist.book_marks
    end



	def create
        @tour = Tour.find(params[:tour_id])
        book_mark = current_tourist.book_marks.new(tour_id: @tour.id)
        if book_mark.save
    # -------- 通知機能　---------
            temp = Notification.where(["tourist_id = ? and guide_id = ? and tour_id = ? and action = ? ", current_tourist.id, @tour.guide.id, @tour.id, 'book_mark'])
            if temp.blank?
                notification = Notification.new(
                    tour_id: @tour.id,
                    tourist_id: current_tourist.id,
                    guide_id: @tour.guide.id,
                    action: "book_mark"
                    )
                notification.save
            end
    # -------- 通知機能　---------
        end
    end


    def destroy
        @tour = Tour.find(params[:tour_id])
        book_mark = current_tourist.book_marks.find_by(tour_id: @tour.id)
        book_mark.destroy
    end




    private
    def correct_tourist
        tourist = Tourist.find(params[:tourist_id])
        if current_tourist != tourist
          redirect_to tourist_tourist_path(current_tourist)
        end
    end

end

app/controllers/tourist/chat_notices_controller.rb
class Tourist::ChatNoticesController < ApplicationController

  before_action :authenticate_tourist!
  before_action :correct_tourist, only: [:index]

  def index
  	@chat_notices = current_tourist.tourist_passive_notices.joins(:message).where('messages.is_tourist = ?',0).page(params[:page]).per(20)
  end

  private
  def correct_tourist
      tourist = Tourist.find(params[:tourist_id])
      if current_tourist != tourist
        redirect_to tourist_tourist_path(current_tourist)
      end
  end

end

# @chat_notices = current_tourist.tourist_passive_notices.page(params[:page]).per(20)
# 上記を用いてview上で条件分岐で「if message.is_tourist == false」としていたが、
# これだとページングで問題が出るため修正した。

app/controllers/tourist/comments_controller.rb
class Tourist::CommentsController < ApplicationController

	before_action :authenticate_tourist!
	before_action :correct_tourist, only: [:create]

	def create
		@tour = Tour.find(params[:tour_id])
		comment = current_tourist.comments.new(comment_params)
		comment.tour_id = @tour.id
		if comment.save
			order = Order.find(params[:order_id])
			order.update(status: "レビュー済み")
		# -------- 通知機能（レビューコメント）--------
			save_notification_comment(comment.id, @tour.guide.id, @tour.id)
		# -------- 通知機能（レビューコメント）--------
			redirect_to tourist_tourist_tour_path(current_tourist, @tour)
		else
			flash[:notice] = "レビューコメントを入力してください"
			redirect_to tourist_tourist_path(current_tourist)
		end
	end





	private
	def comment_params
	  params.require(:comment).permit(:content)
	end

  	def correct_tourist
  		tourist = Tourist.find(params[:tourist_id])
  		if current_tourist != tourist
  		  redirect_to tourist_tourist_path(current_tourist)
  		end
  	end


  # -------- 通知機能（レビューコメント）--------
	def save_notification_comment(comment_id, guide_id, tour_id)
	    notification = current_tourist.notifications.new(
	    	tour_id: tour_id,
	    	guide_id: guide_id,
	    	comment_id: comment_id,
	    	tourist_id: current_tourist,
	     	action: 'comment'
	    )
	    notification.save if notification.valid?
	end
# -------- 通知機能（レビューコメント）--------

end

app/controllers/tourist/messages_controller.rb
class Tourist::MessagesController < ApplicationController

  before_action :authenticate_tourist!
  before_action :correct_tourist, only: [:create]

	def create
    @room = Room.find(params[:room_id])
    @message = Message.new(message_params)
    #メッセージがtouristによるものだったらis_tourist = true, guideによるものだったらis_tourist = false
    @message.is_tourist = true
    @message.room_id = @room.id
    if @message.save
      save_notice_chat!(@message.id, @room.guide.id, @room.id)
      redirect_to tourist_tourist_room_path(current_tourist, @room)
    else
      flash[:warning] = "メッセージを入力してください"
      redirect_to tourist_tourist_room_path(current_tourist, @room)
    end
  end



  private
  def message_params
    params.require(:message).permit(:content)
  end

  def correct_tourist
    tourist = Tourist.find(params[:tourist_id])
    if current_tourist != tourist
      redirect_to tourist_tourist_path(current_tourist)
    end
  end

  def save_notice_chat!(message_id, guide_id, room_id)
      notice = current_tourist.tourist_active_notices.new(
        visitor_id: current_tourist.id,
        visited_id: guide_id,
        message_id: message_id,
        room_id: room_id
      )
      notice.save if notice.valid?
  end

end

app/controllers/tourist/orders_controller.rb
class Tourist::OrdersController < ApplicationController

  before_action :authenticate_tourist!
  before_action :correct_tourist, only: [:new, :confirm, :create, :destroy, :index]

  def index
    @orders = current_tourist.orders
    @comment = Comment.new
  end

  def new
  	@tourist = Tourist.find_by(id: params[:tourist_id])
    @tour = Tour.find_by(id: params[:tour_id])
  	@order = Order.new
  end


  def confirm
  	@order = Order.new(order_params)
  	if @order.companion.to_i + 1 > @order.capacity
      flash[:danger] = "定員数を超えています。"
      redirect_to new_tourist_tourist_order_path(current_tourist, tour_id: @order.tour_id)
    elsif @order.companion == ""
      redirect_to new_tourist_tourist_order_path(current_tourist, tour_id: @order.tour_id)
      flash[:danger] = "0人の場合は0とご入力ください"
    end
  	@order.total_people = @order.companion.to_i + 1
  	@total_price = @order.price * @order.total_people
  end


  def create
  	@order = Order.new(order_params)
  	@order.save
  	redirect_to tourist_orders_thanks_path
  end


  def destroy
    @order = Order.find(params[:id])
    @tourist = @order.tourist
    if @order.status == "ツアー開始前"
      @order.destroy
      redirect_to tourist_tourist_path(@tourist)
    else
      redirect_to tourist_tourist_path(@tourist)
    end
  end


  def thanks
  end


  def show
  end



  private
  def order_params
      params.require(:order).permit(:tourist_id, :tour_id, :guide_id, :tour_title, :tour_body, :price, :contents_of_price, :capacity, :companion, :total_people, :tour_time, :tour_city, :admin_sales, :guide_sales, :tour_genre, :tour_price)
  end

  def correct_tourist
    tourist = Tourist.find(params[:tourist_id])
    if current_tourist != tourist
      redirect_to tourist_tourist_path(current_tourist)
    end
  end



end

app/controllers/tourist/rooms_controller.rb
class Tourist::RoomsController < ApplicationController

  before_action :authenticate_tourist!
  before_action :correct_tourist, only: [:index, :show, :create, :destroy]


  def index
    @rooms = current_tourist.rooms.order(created_at: :desc).page(params[:page]).per(10)
  end


  def show
  	@room = Room.find(params[:id]) #ルーム情報の取得
    @message = Message.new #新規メッセージ投稿
    @messages = @room.messages #このルームのメッセージを全て取得

  # ------ チャット通知機能 -----
    @messages.each do |message|
      if message.is_tourist == false
        message.chat_notices.each do |chat_notice|
          chat_notice.update_attributes(checked: true)
        end
      end
    end
  # ------ チャット通知機能 -----


    if @room.tourist.id == current_tourist.id
      @guide = @room.guide.name
    else
      redirect_to tourist_tourist_path(current_tourist)
    end

  end


  def create
    @room = Room.new(room_guide_params)
    @room.tourist_id = current_tourist.id
    if @room.save
      redirect_to tourist_tourist_room_path(current_tourist, @room)
    else
      redirect_to tourist_tourist_path(current_tourist)
    end
  end




  private
  def room_guide_params
    params.require(:room).permit(:guide_id)
  end

  def correct_tourist
    tourist = Tourist.find(params[:tourist_id])
    if current_tourist != tourist
      redirect_to tourist_tourist_path(current_tourist)
    end
  end

end

app/controllers/tourist/search_controller.rb
class Tourist::SearchController < ApplicationController

  before_action :authenticate_tourist!

  def search
  	if @content = params["search"]["content"]
	    @city = City.match(@content)
	    unless @city.nil?
	    	@tours = @city.tours
	    else
	    	@tours = 0
	    end
	else
		flash[:warning] = "都市名を入力してください"
		redirect_to tourist_tours_path
	end
  end
end

app/controllers/tourist/tourists_controller.rb
class Tourist::TouristsController < ApplicationController

  before_action :authenticate_tourist!, only: [:show, :edit, :update, :destroy]
  before_action :correct_tourist, only: [:show, :edit, :update, :destroy]
  before_action :correct_tourist_for_delete, only: [:delete]


  def show
  end

  def edit
  	@tourist = Tourist.find(params[:id])
  end

  def update
  	@tourist = Tourist.find(params[:id])
  	if @tourist.update(tourist_params)
  		redirect_to tourist_tourist_path(@tourist)
  	else
  		render 'edit'
  	end
  end

  def destroy
    @tourist = Tourist.find(params[:id])
    @tourist.destroy
    redirect_to tourist_tourist_thanks_path
  end

  def delete
  end

  def thanks
  end


  private
  def tourist_params
    params.require(:tourist).permit(:family_name, :name, :nationality, :birth_year, :address, :postal_code, :email, :phone_number, :sex)
  end

  def correct_tourist
    tourist = Tourist.find(params[:id])
    if current_tourist != tourist
      redirect_to tourist_tourist_path(current_tourist)
    end
  end

  def correct_tourist_for_delete
    tourist = Tourist.find(params[:tourist_id])
    if current_tourist != tourist
      redirect_to tourist_tourist_path(current_tourist)
    end
  end

end

app/controllers/tourist/tours_controller.rb
class Tourist::ToursController < ApplicationController

  def index
  	@genres = Genre.all
  	if params[:genre_id]
  		@genre = Genre.find(params[:genre_id])
  		@tours = @genre.tours.order(created_at: :desc).page(params[:page]).per(10)
  	else
  		@tours = Tour.all.page(params[:page]).per(9)
  	end
  end

  def show
  	@tour = Tour.find(params[:id])
    @tour_photos = @tour.tour_photos
    @comments = @tour.comments

    #自分が入ってるroomの相手のidを格納する
    if tourist_signed_in?
      rooms = current_tourist.rooms
      @guide_ids = []
      rooms.each do |room|
        @guide_ids << room.guide_id
      end
    end

  end

end

app/controllers/tourists/confirmations_controller.rb
# frozen_string_literal: true

class Tourists::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/tourists/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Tourists::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/tourists/passwords_controller.rb
# frozen_string_literal: true

class Tourists::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/tourists/unlocks_controller.rb
# frozen_string_literal: true

class Tourists::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/tourists_helper.rb
module Admin::TouristsHelper
end

app/helpers/tourist/book_marks_helper.rb
module Tourist::BookMarksHelper
end

app/helpers/tourist/chat_notices_helper.rb
module Tourist::ChatNoticesHelper
end

app/views/tourist/tourists/_tbody.html.erb
<tr class = "text-center">
	<td><%= order.tour_title %></td>
	<td><%= order.tour_city %></td>
	<td><%= order.total_people %>名</td>
	<td>¥ <%= number_with_delimiter(order.price) %></td>
	<td><%= link_to "ツアー詳細へ", tourist_tourist_tour_path(current_tourist, order.tour_id), class: "btn btn-default" %></td>
</tr>

app/views/tourist/tourists/_thead.html.erb
<thead>
	<tr>
		<th class = "text-center">予約された日</th>
		<th class = "text-center">ツアータイトル</th>
		<th class = "text-center">ツアー都市</th>
		<th class = "text-center">参加人数</th>
		<th class = "text-center">合計金額</th>
	</tr>
</thead>

app/views/tourist/tourists/delete.html.erb
<div class = "container">
	<div class = "row">
		<div class = "col-xs-8 col-xs-offset-1">
			<h3>本当に退会しますか？</h3>
			<span>
				<%= link_to "退会する", tourist_tourist_path(current_tourist), data: { confirm: "本当に退会しますか?" }, method: :delete ,class: "btn btn-danger" %>
			</span>
			<span>
				<%= link_to "退会しない", tourist_tourist_path(current_tourist), class: "btn btn-default" %>
			</span>
		</div>
	</div>
</div>

app/views/tourist/tourists/edit.html.erb
<div class = "container">
	<div class = "row">
		<div class = "col-xs-11">

		<!------- エラーメッセージ ------->
			<% if @tourist.errors.any? %>
			    <div id="error_explanation">
			    	<h2><%= @tourist.errors.count %>件のエラーが発生しました。</h2>
			    	<ul>
					    <% @tourist.errors.full_messages.each do |message| %>
					      <li><%= message %></li>
					    <% end %>
			    	</ul>
			    </div>
		    <% end %>
		<!------- エラーメッセージ ------->

			<h1><%= @tourist.name %>さんの情報変更画面</h1>
			<%= form_for(@tourist, url: tourist_tourist_path(@tourist)) do |f| %>
				<table class = "table table-bordered">
          		<!-- 氏名 -->
		            <tr class = "text-center">
		            	<td class = "active">お名前・国籍・生まれ年</td>
		            	<td>
		            		<%= f.label :姓 %><br/><%= f.text_field :family_name %>
		            	</td>
		            	<td>
		            		<%= f.label :名 %><br/><%= f.text_field :name %>
		            	</td>
		            	<td>
		            		<%= f.label :性別 %><br/><%= f.select :sex,[["女性", "女性"], ["男性", "男性"]], :prompt => "--性別--"  %>
		            	</td>
		            	<td>
		            		<%= f.label :生まれ年 %>(西暦)<br/><%= f.text_field :birth_year %>年
		            	</td>
		            </tr>
		          <!-- 氏名 -->


		          <!-- 住所 -->
		            <tr class = "text-center">
		            	<td class = "active">国籍・電話番号・住所</td>
		            	<td>
		            		<%= f.label :国籍 %><br/><%= f.text_field :nationality %>
		            	</td>
		            	<td>
		            		<%= f.label :電話番号 %><br/><%= f.text_field :phone_number %>
		            	</td>
		            	<td>
		            		<%= f.label :郵便番号 %><br/><%= f.text_field :postal_code %>
		            	</td>
		            	<td>
		            		<%= f.label :住所 %><br/><%= f.text_field :address %>
		            	</td>
		            </tr>
		          <!-- 住所 -->

		          <!-- パスワード -->
		            <tr class = "text-center">
		            	<td class = "active">メールアドレス</td>
		            	<td>
		            		<%= f.label :メールアドレス %><br/><%= f.text_field :email %>
		            	</td>
		            </tr>
          <!-- パスワード -->
		        </table>

				<div class = "row">
					<div class = "col-xs-3">
						<div class="actions">
							<%= f.submit "情報更新", class: "btn btn-success btn-lg" %>
						</div>
					</div>
				</div>
				<!------- 退会ページ ------->
					<div class = "col-xs-1">
						<%= link_to "退会手続きへ", tourist_tourist_tourist_delete_path(current_tourist), class: "btn btn-danger delete-btn btn-xs" %>
					</div>
			<!------- 退会ページ ------->
			<% end %>
		</div>
	</div>
</div>

app/views/tourist/tourists/show.html.erb
<div class = "contaienr">
	<div class = "row">
		<div class = "col-xs-4 col-xs-offset-3">
			<%= link_to  edit_tourist_tourist_path(current_tourist), class: "btn btn-lg" do %>
				<i class="fas fa-address-card fa-10x"></i>
				<h3>個人情報変更</h3>
			<% end %>
		</div>
		<div class = "col-xs-4">
			<%= link_to  tourist_tourist_orders_path(current_tourist), class: "btn btn-lg" do %>
				<i class="far fa-calendar-check fa-10x"></i>
				<h3>予約一覧</h3>
			<% end %>
		</div>
	</div>
	<div class = "row">
		<div class = "col-xs-4 col-xs-offset-3">
			<%= link_to tourist_tourist_rooms_path(current_tourist) do %>
				<% if unchecked_tourist_chat_notices.any? %>
		          <span class = "tourist-chats-mark">
		            <i class="far fa-comments fa-10x"></i>
		            <h2>チャット</h2>
		              <span class = "tourist-chats-mark-circle">
		                <i class="fas fa-circle fa-3x" style = "color: orange;"></i>
		              </span>
		          </span>
		        <% else %>
		        	<i class="far fa-comments fa-10x"></i>
		        	<h2>チャット</h2>
		        <% end %>
		    <% end %>
	    </div>
		<div class = "col-xs-4">
			<%= link_to tourist_tourist_book_mark_path(current_tourist) do %>
                <i class="fas fa-flag fa-10x"></i>
                <h3>ブックマーク</h3>
            <% end %>
		</div>
	</div>
</div>

app/views/tourist/tourists/thanks.html.erb
<div class = "container">
	<div class = "row">
		<div class = "col-xs-8 col-xs-offset-1">
			<h1>
				ご愛用誠にありがとうございました。
			</h1>
		</div>
	</div>
</div>