config/routes.rb
Rails.application.routes.draw do


	#管理者以外のログインアウト後
	root to: 'tour_guide/home#about'


	get 'tour_guide/window' => 'tour_guide/home#window', as: 'home_window'
	get 'home/introduction' => 'tour_guide/home#introduction', as: 'introduction'



	  devise_for :admins, controllers: {
	  sessions:      'admins/sessions',
	  passwords:     'admins/passwords',
	  registrations: 'admins/registrations'
	}

	  devise_for :guides, controllers: {
	  sessions:      'guides/sessions',
	  passwords:     'guides/passwords',
	  registrations: 'guides/registrations'
	}
	devise_scope :guide do
	    post "guides/sign_in_with_guest" => "guides/sessions#guide_guest", as: 'guests_guide'
	end

	devise_for :tourists, controllers: {
	  sessions:      'guides/sessions',
	  passwords:     'guides/passwords',
	  registrations: 'guides/registrations'
	}
	devise_scope :tourist do
	    post "tourists/sign_in_with_guest" => "tourists/sessions#tourist_guest", as: 'guests_tourist'
	end



	# 管理者
	namespace :admin do
	    get 'home/top'
	    get 'search/search'
	    get 'orders/today' => 'orders#today', as: 'orders_today'
	    get 'contacts/thanks' => 'contacts#thanks', as: 'contact_thanks'
	    resources :contacts, only: [:index, :new, :edit, :update, :create]
	    resources :comments, only: [:destroy]
	    resources :cities, only: [:index, :create, :edit, :update, :destroy]
	    resources :rooms, only: [:show, :index, :destroy]
	    resources :genres, only: [:index, :create, :edit, :update, :destroy]
	    resources :guides, only: [:show, :index, :update, :destroy,]
	    resources :tourists, only: [:show, :index, :update, :destroy]
	    resources :orders, only: [:show, :index]
	    resources :tours, only: [:show, :index, :update]
	end



	# ツアーとツアーガイド
	namespace :tour_guide do
	    get 'top' => 'home#top'
		get 'guides/thanks' => 'guides#thanks', as: 'guide_thanks'


	    resources :guides, only: [:show, :edit, :update, :destroy] do
	    	get 'tourists/delete' => 'guides#delete', as: 'guide_delete'
	    	get 'orders/new_order' => 'orders#new_order', as: 'new_order'
	    	get 'orders/around_touring' => 'ordersaround_touring', as: 'around_touring'
	    	get 'orders/finished_tour' => 'orders#finished_tour', as: 'finished_tour'
	    	get 'orders/reviewed_tour' => 'orders#reviewed_tour', as: 'reviewed_tour'
	    	resources :notifications, only: [:index]
	    	resources :orders, only: [:index, :update]
	    	resources :rooms, only: [:show, :index, :create] do
	    		resources :messages, only: [:create]
	    	end
	    	resources :tours do
	    		resource :photos, only: [:new, :create]
	    	end
	    end
	end




	# 観光客
	namespace :tourist do
		get 'search/search'
		get 'orders/thanks' => 'orders#thanks', as: 'orders_thanks'
		get 'tourists/thanks' => 'tourists#thanks', as: 'tourist_thanks'

		resources :tourists, only: [:show, :edit, :update, :destroy] do
			get 'tours/bookmarks' => 'book_marks#index', as: 'book_mark'
			get 'tours/my_account' => 'tourist#my_account', as: 'my_account'
			get 'orders/confirm' => 'orders#confirm', as: 'orders_confirm'
			get 'tourists/delete' => 'tourists#delete', as: 'tourist_delete'
			resources :orders, only: [:show, :index, :new, :create, :destroy]
			resources :chat_notices, only: [:index]
			resources :rooms, only: [:show, :index, :create] do
		    	resources :messages, only: [:create]
		    end
		    resources :tours, only: [:show, :index] do
		    	resources :comments, only: [:create]
				resource :book_marks, only: [:create, :destroy]
			end
		end

	end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/tour.rb
class Tour < ApplicationRecord

	belongs_to :guide, optional: true
	belongs_to :genre, optional: true
	belongs_to :city, optional: true
  has_many :book_marks, dependent: :destroy
  has_many :tour_photos, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :notifications, dependent: :destroy

  # ビューからデータを送る際に、ツアーと一緒にツアー写真を送るための記述
  # reject_if => 指定した条件下においてvalidationを無効にする
  accepts_nested_attributes_for :tour_photos, reject_if: :all_blank, allow_destroy: true

  #ツアーの詳細画面で表示するgooglemap
  geocoded_by :meetingpoint_address
  after_validation :geocode, if: :meetingpoint_address_changed?



  validates :genre_id, presence: true
  validates :city_id, presence: true
  validates :title, presence: true, length: { maximum: 20 }
  validates :body, presence: true, length: { maximum: 400 }
  validates :meetingpoint_introduction, presence: true, length: { maximum: 200 }
  validates :meetingpoint_address, presence: true
  validates :capacity, presence: true
  validates :price, presence: true
  validates :contents_of_price, presence: true
  validates :time, presence: true


  # ブックマーク機能
  def bookmarked_by?(tourist)
    self.book_marks.where(tourist_id: tourist.id).exists?
  end




  # # 通知機能
  # def create_notification_like!(current_tourist)
  #   # すでに「ブックマーク」されているか検索
  #   temp = Notification.where(["visitor_id = ? and visited_id = ? and tour_id = ? and action = ? ", current_tourist.id, guide_id, id, 'like'])
  #   # ブックマークされていない場合のみ、通知レコードを作成
  #   if temp.blank?
  #     notification = current_tourist.new(
  #       post_id: id,
  #       visited_id: guide_id,
  #       action: 'like'
  #     )
  #     # 自分の投稿に対するいいねの場合は、通知済みとする
  #     if notification.visitor_id == notification.visited_id
  #       notification.checked = true
  #     end
  #     notification.save if notification.valid?
  #   end
  # end



end

app/controllers/admin/tours_controller.rb
class Admin::ToursController < ApplicationController
  before_action :authenticate_admin!

  def index
    @genres = Genre.all
  	if params[:genre_id]
  		@genre = Genre.find(params[:genre_id])
  		@tours = @genre.tours.order(created_at: :desc)
  	else
  		@tours = Tour.all
  	end
  end


  def show
  	@tour = Tour.find(params[:id])
    @tour_photos = @tour.tour_photos
    @comments = @tour.comments
  end


  def update
    @tour = Tour.find(params[:id])
    @tour.update(tour_params)
    redirect_to admin_tour_path(@tour)
  end



  private
  def tour_params
    params.require(:tour).permit(:is_active)
  end

end

app/controllers/tour_guide/tours_controller.rb
class TourGuide::ToursController < ApplicationController

  before_action :authenticate_guide!
  before_action :correct_guide, only: [:new, :create, :edit, :update, :destroy]

  def new
  	@tour = Tour.new
    @tour_photo = @tour.tour_photos.build
  end


  def create
  	@tour = Tour.new(tour_params)
  	@tour.guide_id = current_guide.id
  	if @tour.save
  	 redirect_to tour_guide_guide_tour_path(current_guide, @tour)
    else
      render 'new'
    end
  end


  def show
  	@tour = Tour.find(params[:id])
    @tour_photos = @tour.tour_photos
    @comments = @tour.comments
  end


  def index
  	@genres = Genre.all
  	if params[:genre_id]
  		@genre = Genre.find(params[:genre_id])
  		@tours = @genre.tours.order(created_at: :desc).page(params[:page]).per(9)
  	else
  		@tours = Tour.all.order(created_at: :desc).page(params[:page]).per(9)
  	end
  end

  def edit
  	@tour = Tour.find(params[:id])
  end


  def update
  	@tour = Tour.find(params[:id])
  	if@tour.update(tour_params)
  	  redirect_to tour_guide_guide_tour_path(current_guide, @tour)
    else
      render 'edit'
    end
  end


  def destroy
    @tour = Tour.find(params[:id])
    @tour.destroy
    redirect_to tour_guide_guide_path(current_guide)
  end



  private
  def tour_params
  params.require(:tour).permit(:genre_id, :city_id, :title, :body, :capacity, :time, :price,
    :contents_of_price, :meetingpoint_address, :meetingpoint_introduction, :is_active, tour_photos_attributes: [:id, :image, :tour_id, :_destroy])
  end

  def correct_guide
    guide = Guide.find(params[:guide_id])
    if current_guide != guide
      redirect_to tour_guide_guide_path(current_guide)
    end
  end

end

app/controllers/tourist/tours_controller.rb
class Tourist::ToursController < ApplicationController

  def index
  	@genres = Genre.all
  	if params[:genre_id]
  		@genre = Genre.find(params[:genre_id])
  		@tours = @genre.tours.order(created_at: :desc).page(params[:page]).per(10)
  	else
  		@tours = Tour.all.page(params[:page]).per(9)
  	end
  end

  def show
  	@tour = Tour.find(params[:id])
    @tour_photos = @tour.tour_photos
    @comments = @tour.comments

    #自分が入ってるroomの相手のidを格納する
    if tourist_signed_in?
      rooms = current_tourist.rooms
      @guide_ids = []
      rooms.each do |room|
        @guide_ids << room.guide_id
      end
    end

  end

end

app/helpers/admin/tours_helper.rb
module Admin::ToursHelper
end

app/helpers/tour_guide/tours_helper.rb
module TourGuide::ToursHelper
end

app/helpers/tourist/tours_helper.rb
module Tourist::ToursHelper
end

app/views/admin/tours/_tbody.html.erb
<tr class = "text-center">
	<td><%= tour.guide.name %>さん</td>
	<td><%= tour.title %></td>
	<td>
		<% if tour.is_active == true  %>
			販売中
		<% else %>
			販売停止中
		<% end %>
	</td>
	<td><%= tour.city.name %></td>
	<td><%= tour.genre.name %></td>
	<td><%= link_to "ツアー詳細へ", admin_tour_path(tour), class: "btn btn-default" %></td>
</tr>

app/views/admin/tours/index.html.erb
<div class = "admin-tours-index">

<!----- 検索機能 ----->
	<div class = "admin-search-city">
		<p><%= flash[:warning] %></p>
	    <%= form_tag(admin_search_search_path, method: :get) do %>
	      <%= text_field_tag 'search[content]' %>
	      <%= submit_tag '都市名検索', class: "btn btn-primary" %>
	    <% end %>
	</div>
<!----- 検索機能 ----->


	<div class = "container">
		<div class = "row">
			<h1>管理者用ツアー一覧</h1>
			<div class = "col-xs-2">

		<!----- ジャンル検索 ----->
				<div class =  "panel panel-default category-search-box">
					<div class="panel-heading">
						<h3 class="panel-title">ジャンル検索</h3>
					</div>
					<div class = "panel-body" >
						<% @genres.each do |genre| %>
							<p>
								<%= link_to admin_tours_path(genre_id: genre.id) do %>
									<%= genre.name %>
								<% end %>
							</p>
						<% end %>
					</div>
				</div>
				<div class = "text-center">
					<%= link_to "都市投稿", admin_cities_path, class: "btn btn-success btn-lg" %>
				</div>
				<div class = "text-center admin_genre_btn">
					<%= link_to "ジャンル投稿", admin_genres_path, class: "btn btn-info btn-lg" %>
				</div>
			</div>
		<!----- ジャンル検索 ----->

	<!----- ツアー一覧 ----->
			<div class = "col-xs-10">
				<table class = "table">
					<thead>
						<tr class = "active">
							<th class = "text-center">紹介者</th>
							<th class = "text-center">ツアー名</th>
							<th class = "text-center">販売ステータス</th>
							<th class = "text-center">都市</th>
							<th class = "text-center">ジャンル</th>
							<th class = "text-center"></th>
						</tr>
					</thead>
					<% @tours.each do |tour| %>
						<% if tour.is_active == true %>
							<tbody>
								<%= render 'tbody', tour: tour %>
							</tbody>
						<% else %>
							<tbody class = "tour_is_active-tbody">
								<%= render 'tbody', tour: tour %>
							</tbody>
						<% end %>
					<% end %>
				</table>
			</div>
		</div>
	<!----- ツアー一覧 ----->


	</div>
</div>

app/views/admin/tours/show.html.erb
<div class = "tour-top-wrapper">

<!----- ツアー写真 ----->
	<div class = "tour-image-wrapper">
		<span class = "guide_book_marks">
		    <i class="fa fa-flag fa-5x" aria-hidden="true" style = "color: red;" ></i>
		    <span class = "guide_book_marks_numbers"><%= @tour.book_marks.count %></span>
		</span>
		<%= render 'tourist/tours/tour_image_wrapper' %>
	</div>
<!----- ツアー写真 ----->



	<div class = "container">
		<div class = "row">

		<!----- ツアー情報（価格等） ----->
			<%= render 'tourist/tours/tour_info', tour: @tour %>
		<!----- ツアー情報（価格等） ----->

			<div class = "col-xs-2">
				<%= form_for(@tour, url: admin_tour_path(@tour)) do |f| %>
					<% if @tour.is_active == true %>
						<span class="col-xs-3">
							<%= f.radio_button :is_active, true , checked: true %>
							<%= f.label :is_active, "販売" %>
						</span>
						<span class="col-xs-4">
							<%= f.radio_button :is_active, false, checked: false %>
							<%= f.label :is_active, "販売停止" %>
						</span>
						<span class="col-xs-5">
				    <% else %>
						<span class="col-xs-3">
							<%= f.radio_button :is_active, true , checked: false %>
							<%= f.label :is_active, "販売" %>
						</span>
						<span class="col-xs-4">
							<%= f.radio_button :is_active, true, checked: true %>
							<%= f.label :is_active, "販売停止" %>
						</span>
					<% end %>
					<span><%= f.submit "更新", class: "btn btn-success" %></span>
				<% end %>
			</div>
		</div>
	</div>
</div>

<div class = "guide-tour-body-wrapper">
	<div class = "container">
		<% if @tour.is_active == false %>
			<span class = "admin_tour_is_active_false">
				<h1 class = "admin_tour_is_active_false_text">販売停止中</h1>
			</span>
		<% end %>

	<!------- ツアー内容説明 -------->
		<div class = "row">
			<div class = "guide-tour-details">
				<div class = "col-xs-4">
					<div class = "guide-body-title">
						<h2>ツアー内容</h2>
					</div>
				</div>
				<div class = "col-xs-8">
					<h4 class = "guide-body-text"><%= @tour.body %></h4>
				</div>
			</div>
		</div>
	<!------- ツアー内容説明 -------->


	<!------- ツアーガイド紹介 -------->
		<div class = "row">
			<div class = "guide-tour-details">
				<div class = "col-xs-4">
					<div class = "guide-body-title">
						<h2>ガイド紹介</h2>
						<div class = "guide-tour-guide-introduction">
							<%= attachment_image_tag @tour.guide, :selfy_image, :fill, 100, 100, format: 'jpeg' %>
							<h4><strong><%= @tour.guide.family_name %> <%= @tour.guide.name %></strong></h4>
						</div>
					</div>
				</div>
				<div class = "col-xs-8">
					<div class = "tour-body-wrapper">
						<h4 class = "guide-body-text"><%= @tour.guide.introduction %></h4>
					</div>
				</div>
			</div>
		</div>
	<!------- ツアーガイド紹介 -------->

	<!----------- 集合場所 ------------>
		<div class = "row">
			<div class = "guide-tour-details">
				<div class = "col-xs-4">
					<div class = "guide-body-title">
						<h2>集合場所</h2>
					</div>
				</div>
				<div class = "col-xs-8">
					<div class = "tour-body-wrapper">
						<h4 class = "guide-body-text">
							<%= @tour.meetingpoint_address %><br/>
							<%= @tour.meetingpoint_introduction %>
						</h4>

					<!----- GoogleMap ----->
						<div id="map"></div>
						<style>
						    #map {
						    height: 500px;
						    width: 70%;
						  }
						</style>
						<script>
						  function initMap() {
						    var uluru = {lat: <%= @tour.latitude %>, lng: <%= @tour.longitude %>};
						    var map = new google.maps.Map(document.getElementById('map'), {
						      zoom: 16,
						      center: uluru
						    });
						    var marker = new google.maps.Marker({
						      position: uluru,
						      map: map
						    });
						  }
						</script>
						<script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLEMAP'] %>&callback=initMap"
						async defer></script>
						</body>
					<!----- GoogleMap ----->

					</div>
				</div>
			</div>
		</div>
	<!----------- 集合場所 ------------>


	<!----------- レビュー一覧 ------------>
		<div class = "row">
			<div class = "guide-tour-details">
				<div class = "col-xs-4">
					<div class = "guide-body-title">
						<h2>レビュー一覧</h2>
					</div>
				</div>
				<div class = "col-xs-8">
					<div class = "tour-body-wrapper">
						<% if @comments.count == 0 %>
							<% if tourist_signed_in? %>
								<h3>予約して最初のレビュー投稿者になりましょう！</h3>
							<% else %>
								<h3>まだレビューはありません。</h3>
							<% end %>
						<% else %>
							<% @comments.each do |comment| %>
								<div class = "review-message-box">
									<h5>
										<%= comment.tourist.family_name %> <%= comment.tourist.name %>さん
										: <%= comment.created_at.to_s(:datetime_jp) %>
										<span>
											<% if admin_signed_in? %>
												<%= link_to "削除する", admin_comment_path(comment), method: :delete,  class: "btn btn-danger", data: {confirm:'このレビューコメントは不適切な内容を含んでいますか？本当に削除してよろしいですか？。'} %>
											<% end %>
										</span>
									</h5>
									<h4 class = "guide-body-text">
										<%= comment.content %>
									</h4>
								</div>
							<% end %>
						<% end %>
					</div>
				</div>
			</div>
		</div>
	<!----------- レビュー一覧 ------------>

	</div>
</div>