config/routes.rb
Rails.application.routes.draw do


	#管理者以外のログインアウト後
	root to: 'tour_guide/home#about'


	get 'tour_guide/window' => 'tour_guide/home#window', as: 'home_window'
	get 'home/introduction' => 'tour_guide/home#introduction', as: 'introduction'



	  devise_for :admins, controllers: {
	  sessions:      'admins/sessions',
	  passwords:     'admins/passwords',
	  registrations: 'admins/registrations'
	}

	  devise_for :guides, controllers: {
	  sessions:      'guides/sessions',
	  passwords:     'guides/passwords',
	  registrations: 'guides/registrations'
	}
	devise_scope :guide do
	    post "guides/sign_in_with_guest" => "guides/sessions#guide_guest", as: 'guests_guide'
	end

	devise_for :tourists, controllers: {
	  sessions:      'guides/sessions',
	  passwords:     'guides/passwords',
	  registrations: 'guides/registrations'
	}
	devise_scope :tourist do
	    post "tourists/sign_in_with_guest" => "tourists/sessions#tourist_guest", as: 'guests_tourist'
	end



	# 管理者
	namespace :admin do
	    get 'home/top'
	    get 'search/search'
	    get 'orders/today' => 'orders#today', as: 'orders_today'
	    get 'contacts/thanks' => 'contacts#thanks', as: 'contact_thanks'
	    resources :contacts, only: [:index, :new, :edit, :update, :create]
	    resources :comments, only: [:destroy]
	    resources :cities, only: [:index, :create, :edit, :update, :destroy]
	    resources :rooms, only: [:show, :index, :destroy]
	    resources :genres, only: [:index, :create, :edit, :update, :destroy]
	    resources :guides, only: [:show, :index, :update, :destroy,]
	    resources :tourists, only: [:show, :index, :update, :destroy]
	    resources :orders, only: [:show, :index]
	    resources :tours, only: [:show, :index, :update]
	end



	# ツアーとツアーガイド
	namespace :tour_guide do
	    get 'top' => 'home#top'
		get 'guides/thanks' => 'guides#thanks', as: 'guide_thanks'


	    resources :guides, only: [:show, :edit, :update, :destroy] do
	    	get 'tourists/delete' => 'guides#delete', as: 'guide_delete'
	    	get 'orders/new_order' => 'orders#new_order', as: 'new_order'
	    	get 'orders/around_touring' => 'ordersaround_touring', as: 'around_touring'
	    	get 'orders/finished_tour' => 'orders#finished_tour', as: 'finished_tour'
	    	get 'orders/reviewed_tour' => 'orders#reviewed_tour', as: 'reviewed_tour'
	    	resources :notifications, only: [:index]
	    	resources :orders, only: [:index, :update]
	    	resources :rooms, only: [:show, :index, :create] do
	    		resources :messages, only: [:create]
	    	end
	    	resources :tours do
	    		resource :photos, only: [:new, :create]
	    	end
	    end
	end




	# 観光客
	namespace :tourist do
		get 'search/search'
		get 'orders/thanks' => 'orders#thanks', as: 'orders_thanks'
		get 'tourists/thanks' => 'tourists#thanks', as: 'tourist_thanks'

		resources :tourists, only: [:show, :edit, :update, :destroy] do
			get 'tours/bookmarks' => 'book_marks#index', as: 'book_mark'
			get 'tours/my_account' => 'tourist#my_account', as: 'my_account'
			get 'orders/confirm' => 'orders#confirm', as: 'orders_confirm'
			get 'tourists/delete' => 'tourists#delete', as: 'tourist_delete'
			resources :orders, only: [:show, :index, :new, :create, :destroy]
			resources :chat_notices, only: [:index]
			resources :rooms, only: [:show, :index, :create] do
		    	resources :messages, only: [:create]
		    end
		    resources :tours, only: [:show, :index] do
		    	resources :comments, only: [:create]
				resource :book_marks, only: [:create, :destroy]
			end
		end

	end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/admin/tourists_controller.rb
class Admin::TouristsController < ApplicationController

	before_action :authenticate_admin!


  def index
  	@tourists = Tourist.all.with_deleted
  end

  def show
  	@tourist = Tourist.with_deleted.find(params[:id])
    @orders = @tourist.orders
  end

  def update
    @tourist = Tourist.with_deleted.find(params[:id])
      if @tourist.update(tourist_params)
        if tourist_params[:deleted_at].to_i == 0
          flash[:notice] = "情報を更新しました"
           @tourist.restore
           redirect_to admin_tourist_path(@tourist)
        else
          flash[:notice] = "情報を更新しました"
           @tourist.destroy
           redirect_to admin_tourist_path(@tourist)
        end
      else
        flash[:notice] = "情報の更新に失敗しました"
         render 'edit'
      end
  end

  private
  def tourist_params
    params.require(:tourist).permit(:deleted_at)
  end

end

app/controllers/admin/tours_controller.rb
class Admin::ToursController < ApplicationController
  before_action :authenticate_admin!

  def index
    @genres = Genre.all
  	if params[:genre_id]
  		@genre = Genre.find(params[:genre_id])
  		@tours = @genre.tours.order(created_at: :desc)
  	else
  		@tours = Tour.all
  	end
  end


  def show
  	@tour = Tour.find(params[:id])
    @tour_photos = @tour.tour_photos
    @comments = @tour.comments
  end


  def update
    @tour = Tour.find(params[:id])
    @tour.update(tour_params)
    redirect_to admin_tour_path(@tour)
  end



  private
  def tour_params
    params.require(:tour).permit(:is_active)
  end

end

app/controllers/tour_guide/tours_controller.rb
class TourGuide::ToursController < ApplicationController

  before_action :authenticate_guide!
  before_action :correct_guide, only: [:new, :create, :edit, :update, :destroy]

  def new
  	@tour = Tour.new
    @tour_photo = @tour.tour_photos.build
  end


  def create
  	@tour = Tour.new(tour_params)
  	@tour.guide_id = current_guide.id
  	if @tour.save
  	 redirect_to tour_guide_guide_tour_path(current_guide, @tour)
    else
      render 'new'
    end
  end


  def show
  	@tour = Tour.find(params[:id])
    @tour_photos = @tour.tour_photos
    @comments = @tour.comments
  end


  def index
  	@genres = Genre.all
  	if params[:genre_id]
  		@genre = Genre.find(params[:genre_id])
  		@tours = @genre.tours.order(created_at: :desc).page(params[:page]).per(9)
  	else
  		@tours = Tour.all.order(created_at: :desc).page(params[:page]).per(9)
  	end
  end

  def edit
  	@tour = Tour.find(params[:id])
  end


  def update
  	@tour = Tour.find(params[:id])
  	if@tour.update(tour_params)
  	  redirect_to tour_guide_guide_tour_path(current_guide, @tour)
    else
      render 'edit'
    end
  end


  def destroy
    @tour = Tour.find(params[:id])
    @tour.destroy
    redirect_to tour_guide_guide_path(current_guide)
  end



  private
  def tour_params
  params.require(:tour).permit(:genre_id, :city_id, :title, :body, :capacity, :time, :price,
    :contents_of_price, :meetingpoint_address, :meetingpoint_introduction, :is_active, tour_photos_attributes: [:id, :image, :tour_id, :_destroy])
  end

  def correct_guide
    guide = Guide.find(params[:guide_id])
    if current_guide != guide
      redirect_to tour_guide_guide_path(current_guide)
    end
  end

end

app/controllers/tourist/book_marks_controller.rb
class Tourist::BookMarksController < ApplicationController

    before_action :authenticate_tourist!
    before_action :correct_tourist, only: [:create, :destroy, :index]


    def index
        @book_marks = current_tourist.book_marks
    end



	def create
        @tour = Tour.find(params[:tour_id])
        book_mark = current_tourist.book_marks.new(tour_id: @tour.id)
        if book_mark.save
    # -------- 通知機能　---------
            temp = Notification.where(["tourist_id = ? and guide_id = ? and tour_id = ? and action = ? ", current_tourist.id, @tour.guide.id, @tour.id, 'book_mark'])
            if temp.blank?
                notification = Notification.new(
                    tour_id: @tour.id,
                    tourist_id: current_tourist.id,
                    guide_id: @tour.guide.id,
                    action: "book_mark"
                    )
                notification.save
            end
    # -------- 通知機能　---------
        end
    end


    def destroy
        @tour = Tour.find(params[:tour_id])
        book_mark = current_tourist.book_marks.find_by(tour_id: @tour.id)
        book_mark.destroy
    end




    private
    def correct_tourist
        tourist = Tourist.find(params[:tourist_id])
        if current_tourist != tourist
          redirect_to tourist_tourist_path(current_tourist)
        end
    end

end

app/controllers/tourist/chat_notices_controller.rb
class Tourist::ChatNoticesController < ApplicationController

  before_action :authenticate_tourist!
  before_action :correct_tourist, only: [:index]

  def index
  	@chat_notices = current_tourist.tourist_passive_notices.joins(:message).where('messages.is_tourist = ?',0).page(params[:page]).per(20)
  end

  private
  def correct_tourist
      tourist = Tourist.find(params[:tourist_id])
      if current_tourist != tourist
        redirect_to tourist_tourist_path(current_tourist)
      end
  end

end

# @chat_notices = current_tourist.tourist_passive_notices.page(params[:page]).per(20)
# 上記を用いてview上で条件分岐で「if message.is_tourist == false」としていたが、
# これだとページングで問題が出るため修正した。

app/controllers/tourist/comments_controller.rb
class Tourist::CommentsController < ApplicationController

	before_action :authenticate_tourist!
	before_action :correct_tourist, only: [:create]

	def create
		@tour = Tour.find(params[:tour_id])
		comment = current_tourist.comments.new(comment_params)
		comment.tour_id = @tour.id
		if comment.save
			order = Order.find(params[:order_id])
			order.update(status: "レビュー済み")
		# -------- 通知機能（レビューコメント）--------
			save_notification_comment(comment.id, @tour.guide.id, @tour.id)
		# -------- 通知機能（レビューコメント）--------
			redirect_to tourist_tourist_tour_path(current_tourist, @tour)
		else
			flash[:notice] = "レビューコメントを入力してください"
			redirect_to tourist_tourist_path(current_tourist)
		end
	end





	private
	def comment_params
	  params.require(:comment).permit(:content)
	end

  	def correct_tourist
  		tourist = Tourist.find(params[:tourist_id])
  		if current_tourist != tourist
  		  redirect_to tourist_tourist_path(current_tourist)
  		end
  	end


  # -------- 通知機能（レビューコメント）--------
	def save_notification_comment(comment_id, guide_id, tour_id)
	    notification = current_tourist.notifications.new(
	    	tour_id: tour_id,
	    	guide_id: guide_id,
	    	comment_id: comment_id,
	    	tourist_id: current_tourist,
	     	action: 'comment'
	    )
	    notification.save if notification.valid?
	end
# -------- 通知機能（レビューコメント）--------

end

app/controllers/tourist/messages_controller.rb
class Tourist::MessagesController < ApplicationController

  before_action :authenticate_tourist!
  before_action :correct_tourist, only: [:create]

	def create
    @room = Room.find(params[:room_id])
    @message = Message.new(message_params)
    #メッセージがtouristによるものだったらis_tourist = true, guideによるものだったらis_tourist = false
    @message.is_tourist = true
    @message.room_id = @room.id
    if @message.save
      save_notice_chat!(@message.id, @room.guide.id, @room.id)
      redirect_to tourist_tourist_room_path(current_tourist, @room)
    else
      flash[:warning] = "メッセージを入力してください"
      redirect_to tourist_tourist_room_path(current_tourist, @room)
    end
  end



  private
  def message_params
    params.require(:message).permit(:content)
  end

  def correct_tourist
    tourist = Tourist.find(params[:tourist_id])
    if current_tourist != tourist
      redirect_to tourist_tourist_path(current_tourist)
    end
  end

  def save_notice_chat!(message_id, guide_id, room_id)
      notice = current_tourist.tourist_active_notices.new(
        visitor_id: current_tourist.id,
        visited_id: guide_id,
        message_id: message_id,
        room_id: room_id
      )
      notice.save if notice.valid?
  end

end

app/controllers/tourist/orders_controller.rb
class Tourist::OrdersController < ApplicationController

  before_action :authenticate_tourist!
  before_action :correct_tourist, only: [:new, :confirm, :create, :destroy, :index]

  def index
    @orders = current_tourist.orders
    @comment = Comment.new
  end

  def new
  	@tourist = Tourist.find_by(id: params[:tourist_id])
    @tour = Tour.find_by(id: params[:tour_id])
  	@order = Order.new
  end


  def confirm
  	@order = Order.new(order_params)
  	if @order.companion.to_i + 1 > @order.capacity
      flash[:danger] = "定員数を超えています。"
      redirect_to new_tourist_tourist_order_path(current_tourist, tour_id: @order.tour_id)
    elsif @order.companion == ""
      redirect_to new_tourist_tourist_order_path(current_tourist, tour_id: @order.tour_id)
      flash[:danger] = "0人の場合は0とご入力ください"
    end
  	@order.total_people = @order.companion.to_i + 1
  	@total_price = @order.price * @order.total_people
  end


  def create
  	@order = Order.new(order_params)
  	@order.save
  	redirect_to tourist_orders_thanks_path
  end


  def destroy
    @order = Order.find(params[:id])
    @tourist = @order.tourist
    if @order.status == "ツアー開始前"
      @order.destroy
      redirect_to tourist_tourist_path(@tourist)
    else
      redirect_to tourist_tourist_path(@tourist)
    end
  end


  def thanks
  end


  def show
  end



  private
  def order_params
      params.require(:order).permit(:tourist_id, :tour_id, :guide_id, :tour_title, :tour_body, :price, :contents_of_price, :capacity, :companion, :total_people, :tour_time, :tour_city, :admin_sales, :guide_sales, :tour_genre, :tour_price)
  end

  def correct_tourist
    tourist = Tourist.find(params[:tourist_id])
    if current_tourist != tourist
      redirect_to tourist_tourist_path(current_tourist)
    end
  end



end

app/controllers/tourist/rooms_controller.rb
class Tourist::RoomsController < ApplicationController

  before_action :authenticate_tourist!
  before_action :correct_tourist, only: [:index, :show, :create, :destroy]


  def index
    @rooms = current_tourist.rooms.order(created_at: :desc).page(params[:page]).per(10)
  end


  def show
  	@room = Room.find(params[:id]) #ルーム情報の取得
    @message = Message.new #新規メッセージ投稿
    @messages = @room.messages #このルームのメッセージを全て取得

  # ------ チャット通知機能 -----
    @messages.each do |message|
      if message.is_tourist == false
        message.chat_notices.each do |chat_notice|
          chat_notice.update_attributes(checked: true)
        end
      end
    end
  # ------ チャット通知機能 -----


    if @room.tourist.id == current_tourist.id
      @guide = @room.guide.name
    else
      redirect_to tourist_tourist_path(current_tourist)
    end

  end


  def create
    @room = Room.new(room_guide_params)
    @room.tourist_id = current_tourist.id
    if @room.save
      redirect_to tourist_tourist_room_path(current_tourist, @room)
    else
      redirect_to tourist_tourist_path(current_tourist)
    end
  end




  private
  def room_guide_params
    params.require(:room).permit(:guide_id)
  end

  def correct_tourist
    tourist = Tourist.find(params[:tourist_id])
    if current_tourist != tourist
      redirect_to tourist_tourist_path(current_tourist)
    end
  end

end

app/controllers/tourist/search_controller.rb
class Tourist::SearchController < ApplicationController

  before_action :authenticate_tourist!

  def search
  	if @content = params["search"]["content"]
	    @city = City.match(@content)
	    unless @city.nil?
	    	@tours = @city.tours
	    else
	    	@tours = 0
	    end
	else
		flash[:warning] = "都市名を入力してください"
		redirect_to tourist_tours_path
	end
  end
end

app/controllers/tourist/tourists_controller.rb
class Tourist::TouristsController < ApplicationController

  before_action :authenticate_tourist!, only: [:show, :edit, :update, :destroy]
  before_action :correct_tourist, only: [:show, :edit, :update, :destroy]
  before_action :correct_tourist_for_delete, only: [:delete]


  def show
  end

  def edit
  	@tourist = Tourist.find(params[:id])
  end

  def update
  	@tourist = Tourist.find(params[:id])
  	if @tourist.update(tourist_params)
  		redirect_to tourist_tourist_path(@tourist)
  	else
  		render 'edit'
  	end
  end

  def destroy
    @tourist = Tourist.find(params[:id])
    @tourist.destroy
    redirect_to tourist_tourist_thanks_path
  end

  def delete
  end

  def thanks
  end


  private
  def tourist_params
    params.require(:tourist).permit(:family_name, :name, :nationality, :birth_year, :address, :postal_code, :email, :phone_number, :sex)
  end

  def correct_tourist
    tourist = Tourist.find(params[:id])
    if current_tourist != tourist
      redirect_to tourist_tourist_path(current_tourist)
    end
  end

  def correct_tourist_for_delete
    tourist = Tourist.find(params[:tourist_id])
    if current_tourist != tourist
      redirect_to tourist_tourist_path(current_tourist)
    end
  end

end

app/controllers/tourist/tours_controller.rb
class Tourist::ToursController < ApplicationController

  def index
  	@genres = Genre.all
  	if params[:genre_id]
  		@genre = Genre.find(params[:genre_id])
  		@tours = @genre.tours.order(created_at: :desc).page(params[:page]).per(10)
  	else
  		@tours = Tour.all.page(params[:page]).per(9)
  	end
  end

  def show
  	@tour = Tour.find(params[:id])
    @tour_photos = @tour.tour_photos
    @comments = @tour.comments

    #自分が入ってるroomの相手のidを格納する
    if tourist_signed_in?
      rooms = current_tourist.rooms
      @guide_ids = []
      rooms.each do |room|
        @guide_ids << room.guide_id
      end
    end

  end

end

app/controllers/tourists/unlocks_controller.rb
# frozen_string_literal: true

class Tourists::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/views/tourist/tours/_about_first_wrapper.html.erb
<div class = "img1"></div>
<div class = "img2"></div>
<div class = "img3"></div>
<div class = "img4"></div>
<div class = "img5"></div>
<div class = "img6"></div>
<div class = "img7"></div>
<div class = "img8"></div>
<div class = "img9"></div>
<div class = "img10"></div>

app/views/tourist/tours/_tour_body_wrapper.html.erb
<div class = "guide-tour-body-wrapper">
	<div class = "container">

	<!------- ツアー内容説明 -------->
		<div class = "row">
			<% if guide_signed_in? %>
				<% if @tour.is_active == false %>
					<span class = "is_actice_false">
						<h1 class = "is_actice_false_text">販売停止中</h1>
					</span>
				<% end %>
			<% end %>
			<div class = "guide-tour-details">
				<div class = "col-xs-4">
					<div class = "guide-body-title">
						<h2>ツアー内容</h2>
					</div>
				</div>
				<div class = "col-xs-8">
					<h4 class = "guide-body-text"><%= tour.body %></h4>
				</div>
			</div>
		</div>
	<!------- ツアー内容説明 -------->



	<!------- ツアーガイド紹介 -------->
		<div class = "row">
			<div class = "guide-tour-details">
				<div class = "col-xs-4">
					<div class = "guide-body-title">
						<h2>ガイド紹介</h2>
						<div class = "guide-tour-guide-introduction">
						<%= attachment_image_tag tour.guide, :selfy_image, :fill, 100, 100, format: 'jpeg' %>
						<h4><strong><%= tour.guide.family_name %> <%= tour.guide.name %></strong></h4>
					</div>
					</div>

				<!----- チャット機能 ----->
					<% if tourist_signed_in? %>
						<div class = "chat-room-btn">
							<% if guide_ids.include?(tour.guide.id) %>
								<%= link_to "質問しましょう！", tourist_tourist_room_path(current_tourist, current_tourist.rooms.find_by(guide_id: tour.guide.id)), class: "btn btn-default" %>
							<% else %>
							    <%= form_for(Room.new, url: tourist_tourist_rooms_path(current_tourist)) do |f| %>
							    	<%= f.hidden_field :guide_id, :value => tour.guide.id %>
							    	<%= f.submit "質問しましょう！", class: "btn btn-default" %>
							    <% end %>
							<% end %>
						</div>
					<% end %>
				<!----- チャット機能 ----->

				</div>
				<div class = "col-xs-8">
					<div class = "tour-body-wrapper">
						<% if guide_signed_in? %>
							<% if current_guide == tour.guide %>
								<% if tour.guide.introduction.nil? %>
									<h3 class = "guide-introduction-blank">
										<%= link_to "登録情報編集画面", edit_tour_guide_guide_path(current_guide) %>
										からあなたについて紹介文を書きましょう！
									</h3>
								<% else %>
									<h4 class = "guide-body-text"><%= tour.guide.introduction %></h4>
								<% end %>
							<% end %>
						<% else %>
							<h4 class = "guide-body-text"><%= tour.guide.introduction %></h4>
						<% end %>
					</div>
				</div>
			</div>
		</div>
	<!------- ツアーガイド紹介 -------->


	<!----------- 集合場所 ------------>
		<div class = "row">
			<div class = "guide-tour-details">
				<div class = "col-xs-4">
					<div class = "guide-body-title">
						<h2>集合場所</h2>
					</div>
				</div>
				<div class = "col-xs-8">
					<div class = "tour-body-wrapper">
						<h4 class = "guide-body-text">
							<%= tour.meetingpoint_address %><br/>
							<%= tour.meetingpoint_introduction %>
						</h4>

					<!----- GoogleMap ----->
						<div id="map"></div>
						<style>
						    #map {
						    height: 500px;
						    width: 70%;
						  }
						</style>
						<script>
						  function initMap() {
						    var uluru = {lat: <%= tour.latitude %>, lng: <%= tour.longitude %>};
						    var map = new google.maps.Map(document.getElementById('map'), {
						      zoom: 16,
						      center: uluru
						    });
						    var marker = new google.maps.Marker({
						      position: uluru,
						      map: map
						    });
						  }
						</script>
						<script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLEMAP'] %>&callback=initMap"
						async defer></script>
						</body>
					<!----- GoogleMap ----->

					</div>
				</div>
			</div>
		</div>
	<!----------- 集合場所 ------------>




	<!----------- レビュー一覧 ------------>
		<div class = "row">
			<div class = "guide-tour-details">
				<div class = "col-xs-4">
					<div class = "guide-body-title">
						<h2>レビュー一覧</h2>
					</div>
				</div>
				<div class = "col-xs-8">
					<div class = "tour-body-wrapper">
						<% if @comments.count == 0 %>
							<% if tourist_signed_in? %>
								<h3>予約して最初のレビュー投稿者になりましょう！</h3>
							<% else %>
								<h3>まだレビューはありません。</h3>
							<% end %>
						<% else %>
							<% comments.each do |comment| %>
								<div class = "review-message-box">
									<h5>
										<%= comment.tourist.family_name %> <%= comment.tourist.name %>さん
										: <%= comment.created_at.to_s(:datetime_jp) %>
										<span>
											<% if admin_signed_in? %>
												<%= link_to "削除する", admin_comment_path(comment), method: :delete,  class: "btn btn-danger", data: {confirm:'このレビューコメントは不適切な内容を含んでいますか？本当に削除してよろしいですか？。'} %>
											<% end %>
										</span>
									</h5>
									<h4 class = "guide-body-text">
										<%= comment.content %>
									</h4>
								</div>
							<% end %>
						<% end %>
					</div>
				</div>
			</div>
		</div>
	<!----------- レビュー一覧 ------------>


	</div>
</div>

app/views/tourist/tours/_tour_photos.html.erb
<% tours.each do |tour| %>
	<% if tour.is_active == true %>
		<div class = "col-xs-4">
			<% @tour_photos = tour.tour_photos %>
			<%= link_to tourist_tourist_tour_path(current_tourist, tour) do %>
				<%= attachment_image_tag @tour_photos[0], :image, :fill, 350, 200, format: 'jpeg',class: "tour-tour-photos-index" %>
				<h3><%= tour.title %>    ¥ <%= number_with_delimiter(tour.price) %></h3>

			<!----- ブックマーク機能 ----->
				<% if tourist_signed_in? %>
					<div class = "show-book-mark">
						<div id = "book_marks_<%= tour.id %>">
							<%= render 'tourist/book_marks/book_mark', tour: tour %>
						</div>
					</div>
				<% end %>
			<!----- ブックマーク機能 ----->

			<% end %>
		</div>
	<% end %>
<% end %>

app/views/tourist/tours/index.html.erb
<!------ トップ画像 ------>

<div class = "about-first-wrapper">
	<div id = "theTarget2">
	    <%= render 'about_first_wrapper' %>
	</div>
</div>
<!------ トップ画像 ------>



<!------ ジャンル ------>
<div class = "tourist-second-wrapper">
	<div class = "container">
		<div class = "row">

			<div class = "col-xs-4 col-xs-offset-1">
				<h3 class = "tourist-headline">ここから旅を始めましょう</h3>
			</div>

		<!-- ジャンル選択 -->
		    <div class= "col-xs-5 col-xs-offset-2">
				<% @genres.each do |genre| %>
					<%= link_to tourist_tourist_tours_path(current_tourist, genre_id: genre.id), class: "btn btn-default tourist-genre-btn" do %>
						<% genre.name %>
					<% end %>
				<% end %>
			</div>
		<!-- ジャンル選択 -->

		</div>
	</div>
</div>
<!------ ジャンル ------>



<!------ ツアー一覧  --------->
<div class = "container">
	<div class = "row">
		<h2>気になる写真をブックマークしましょう！</h2>
		<%= render 'tour_photos', tours: @tours %>
	</div>
	<%= paginate @tours, class: "paginate" %>
</div>
<!------ ツアー一覧  --------->

app/views/tourist/tours/show.html.erb
<div class = "tour-image-wrapper">
<!-- ブックマーク -->
	<% if tourist_signed_in? %>
		<span class = "book_mark">
			<div id = "book_marks_<%= @tour.id %>">
				<%= render 'tourist/book_marks/book_mark', tour: @tour %>
			</div>
		</span>
	<% end %>
<!-- ブックマーク -->

<!----- ツアー写真 ----->
	<%= render 'tour_image_wrapper' %>
<!----- ツアー写真 ----->
</div>





<!------- ツアー情報詳細 -------->
<div class = "tour-info-wrapper">
	<div class = "container">
		<div class = "row">
		<!----- ツアー情報（価格等） ----->
			<%= render 'tour_info', tour: @tour %>
		<!----- ツアー情報（価格等） ----->
			<div class = "col-xs-2">
				<div class = "order-btn">
					<% if tourist_signed_in? %>
						<%= link_to "予約に進む", new_tourist_tourist_order_path(current_tourist, tour_id: @tour.id), class: "btn btn-success btn-lg"  %>
					<% else %>
						<%= link_to "登録して予約しましょう", new_tourist_registration_path, class: "btn btn-success btn-lg"  %>
					<% end %>
				</div>
			</div>
		</div>
	</div>
</div>
<!------- ツアー情報詳細 -------->



<!-- ツアー情報（テキスト） -->
<%= render 'tour_body_wrapper', tour: @tour, guide_ids: @guide_ids, comments: @comments %>
<!-- ツアー情報（テキスト） -->