config/routes.rb
Rails.application.routes.draw do


	#管理者以外のログインアウト後
	root to: 'tour_guide/home#about'


	get 'tour_guide/window' => 'tour_guide/home#window', as: 'home_window'
	get 'home/introduction' => 'tour_guide/home#introduction', as: 'introduction'



	  devise_for :admins, controllers: {
	  sessions:      'admins/sessions',
	  passwords:     'admins/passwords',
	  registrations: 'admins/registrations'
	}

	  devise_for :guides, controllers: {
	  sessions:      'guides/sessions',
	  passwords:     'guides/passwords',
	  registrations: 'guides/registrations'
	}
	devise_scope :guide do
	    post "guides/sign_in_with_guest" => "guides/sessions#guide_guest", as: 'guests_guide'
	end

	devise_for :tourists, controllers: {
	  sessions:      'guides/sessions',
	  passwords:     'guides/passwords',
	  registrations: 'guides/registrations'
	}
	devise_scope :tourist do
	    post "tourists/sign_in_with_guest" => "tourists/sessions#tourist_guest", as: 'guests_tourist'
	end



	# 管理者
	namespace :admin do
	    get 'home/top'
	    get 'search/search'
	    get 'orders/today' => 'orders#today', as: 'orders_today'
	    get 'contacts/thanks' => 'contacts#thanks', as: 'contact_thanks'
	    resources :contacts, only: [:index, :new, :edit, :update, :create]
	    resources :comments, only: [:destroy]
	    resources :cities, only: [:index, :create, :edit, :update, :destroy]
	    resources :rooms, only: [:show, :index, :destroy]
	    resources :genres, only: [:index, :create, :edit, :update, :destroy]
	    resources :guides, only: [:show, :index, :update, :destroy,]
	    resources :tourists, only: [:show, :index, :update, :destroy]
	    resources :orders, only: [:show, :index]
	    resources :tours, only: [:show, :index, :update]
	end



	# ツアーとツアーガイド
	namespace :tour_guide do
	    get 'top' => 'home#top'
		get 'guides/thanks' => 'guides#thanks', as: 'guide_thanks'


	    resources :guides, only: [:show, :edit, :update, :destroy] do
	    	get 'tourists/delete' => 'guides#delete', as: 'guide_delete'
	    	get 'orders/new_order' => 'orders#new_order', as: 'new_order'
	    	get 'orders/around_touring' => 'ordersaround_touring', as: 'around_touring'
	    	get 'orders/finished_tour' => 'orders#finished_tour', as: 'finished_tour'
	    	get 'orders/reviewed_tour' => 'orders#reviewed_tour', as: 'reviewed_tour'
	    	resources :notifications, only: [:index]
	    	resources :orders, only: [:index, :update]
	    	resources :rooms, only: [:show, :index, :create] do
	    		resources :messages, only: [:create]
	    	end
	    	resources :tours do
	    		resource :photos, only: [:new, :create]
	    	end
	    end
	end




	# 観光客
	namespace :tourist do
		get 'search/search'
		get 'orders/thanks' => 'orders#thanks', as: 'orders_thanks'
		get 'tourists/thanks' => 'tourists#thanks', as: 'tourist_thanks'

		resources :tourists, only: [:show, :edit, :update, :destroy] do
			get 'tours/bookmarks' => 'book_marks#index', as: 'book_mark'
			get 'tours/my_account' => 'tourist#my_account', as: 'my_account'
			get 'orders/confirm' => 'orders#confirm', as: 'orders_confirm'
			get 'tourists/delete' => 'tourists#delete', as: 'tourist_delete'
			resources :orders, only: [:show, :index, :new, :create, :destroy]
			resources :chat_notices, only: [:index]
			resources :rooms, only: [:show, :index, :create] do
		    	resources :messages, only: [:create]
		    end
		    resources :tours, only: [:show, :index] do
		    	resources :comments, only: [:create]
				resource :book_marks, only: [:create, :destroy]
			end
		end

	end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
	belongs_to :tourist
	belongs_to :guide

	# enum order_status: { before_starting: 0, tour_day: 1, touring: 2, finised: 3 }
	enum status: { ツアー開始前: 0,ツアー前日: 1, ツアー当日: 2, ツアー中: 3, ツアー終了: 4, レビュー済み: 5 }
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!

  def today
    @orders = Order.where(created_at: Time.zone.now.all_day)
    admin_total_sales = []
    @orders.each do |order|
      admin_total_sales << order.admin_sales
    end
    @admin_total_sales = admin_total_sales.sum
  end

  def index
  	@orders = Order.all
  	admin_total_sales = []
  	@orders.each do |order|
  		admin_total_sales << order.admin_sales
  	end
  	@admin_total_sales = admin_total_sales.sum
  end

  def show
    @order = Order.find(params[:id])
  end

end

app/controllers/tour_guide/guides_controller.rb
class TourGuide::GuidesController < ApplicationController

    before_action :authenticate_guide!, only: [:show, :edit, :update, :destroy]
    before_action :correct_guide_for_delete, only:[:delete]
    before_action :correct_guide, only: [:show, :edit, :update, :destroy]


  def show
  	@guide = Guide.find(params[:id])
  	@tours = @guide.tours
  end

  def edit
  	@guide = Guide.find(params[:id])
  end

  def update
  	@guide = Guide.find(params[:id])
  	if @guide.update(guide_params)
  		redirect_to tour_guide_guide_path(@guide)
  	else
  		render 'edit'
  	end
  end

  def destroy
    @guide = Guide.find(params[:id])
    @guide.destroy
    redirect_to tour_guide_guide_thanks_path
  end

  def delete
  end

  def thanks
  end


  private
  def guide_params
    params.require(:guide).permit(:family_name, :name, :address, :postal_code, :email, :phone_number, :identification_image, :selfy_image, :introduction_image, :introduction)
  end


  def correct_guide
    guide = Guide.find(params[:id])
    if current_guide != guide
      redirect_to tour_guide_guide_path(current_guide)
    end
  end


  def correct_guide_for_delete
    guide = Guide.find(params[:guide_id])
    if current_guide != guide
      redirect_to tour_guide_guide_path(current_guide)
    end
  end



end

app/controllers/tour_guide/home_controller.rb
class TourGuide::HomeController < ApplicationController

  before_action :authenticate_guide!, only: [:top]

  def top
  	@orders = current_guide.orders.where(created_at: Time.zone.now.all_day)
  end

  def about
  	@tours = Tour.all.order(created_at: :desc).page(params[:page]).per(9)
  end

  def window
  	@tour = Tour.find(params[:tour_id])
  	@tour_photos = @tour.tour_photos
    @comments = @tour.comments
  end

  def introduction
  end

end

app/controllers/tour_guide/messages_controller.rb
class TourGuide::MessagesController < ApplicationController

  before_action :authenticate_guide!, only: [:create]
  before_action :correct_guide, only: [:create]

  def create
  	@room = Room.find(params[:room_id])
    @message = Message.new(message_params)
    #メッセージがguideによるものだったらis_tourist = false
    @message.is_tourist = false
    @message.room_id = @room.id
    if @message.save
  # ------- 通知機能 --------
      save_notice_chat!(@message.id, @room.tourist.id, @room.id)
  # ------- 通知機能 --------
      redirect_to tour_guide_guide_room_path(current_guide, @room)
    else
      flash[:warning] = "メッセージを入力してください"
      redirect_to tour_guide_guide_room_path(current_guide, @room)
    end
  end






  private
  def message_params
    params.require(:message).permit(:content)
  end

  def correct_guide
    guide = Guide.find(params[:guide_id])
    if current_guide != guide
      redirect_to tour_guide_guide_path(current_guide)
    end
  end


  def save_notice_chat!(message_id, tourist_id, room_id)
      notice = current_guide.guide_active_notices.new(
        visitor_id: current_guide.id,
        visited_id: tourist_id,
        message_id: message_id,
        room_id: room_id
      )
      notice.save if notice.valid?
  end


end

app/controllers/tour_guide/notifications_controller.rb
class TourGuide::NotificationsController < ApplicationController

  before_action :authenticate_guide!
  before_action :correct_guide

  # 未確認の通知レコードだけ取り出したあと、「未確認→確認済」
  def index
  	@notifications = current_guide.notifications.page(params[:page]).per(20)
    @notifications.where(checked: false).each do |notification|
      notification.update_attributes(checked: true)
    end
  end



  private
  def correct_guide
    guide = Guide.find(params[:guide_id])
    if current_guide != guide
      redirect_to tour_guide_guide_path(current_guide)
    end
  end


end

app/controllers/tour_guide/orders_controller.rb
class TourGuide::OrdersController < ApplicationController

  before_action :authenticate_guide!
  before_action :correct_guide, only: [:index, :update]


  def update
    @order = Order.find(params[:id])
    if @order.update(order_params)
      flash[:notice] = "予約ステータスを更新しました"
      redirect_to tour_guide_guide_orders_path(current_guide)
    end
  end

  def index
    @orders = current_guide.orders
    @todays_orders = current_guide.orders.where(created_at: Time.zone.now.all_day)
    guide_total_sales = []
    @orders.each do |order|
      guide_total_sales << order.guide_sales
    end
    @guide_total_sales = guide_total_sales.sum
    @guide_total_sales = @guide_total_sales.floor

    rooms = current_guide.rooms
    @tourist_ids = []
    rooms.each do |room|
      @tourist_ids << room.tourist_id
    end
  end


# -------------- 予約ステータス変更ページ --------------
  def new_order
    @orders = current_guide.orders
    guide_total_sales = []
    @orders.each do |order|
      guide_total_sales << order.guide_sales
    end
    @guide_total_sales = guide_total_sales.sum
    @guide_total_sales = @guide_total_sales.floor

    rooms = current_guide.rooms
    @tourist_ids = []
    rooms.each do |room|
      @tourist_ids << room.tourist_id
    end
  end


  def around_touring
    @orders = current_guide.orders
    guide_total_sales = []
    @orders.each do |order|
      guide_total_sales << order.guide_sales
    end
    @guide_total_sales = guide_total_sales.sum
    @guide_total_sales = @guide_total_sales.floor

    rooms = current_guide.rooms
    @tourist_ids = []
    rooms.each do |room|
      @tourist_ids << room.tourist_id
    end
  end

  def finished_tour
    @orders = current_guide.orders
    guide_total_sales = []
    @orders.each do |order|
      guide_total_sales << order.guide_sales
    end
    @guide_total_sales = guide_total_sales.sum
    @guide_total_sales = @guide_total_sales.floor

    rooms = current_guide.rooms
    @tourist_ids = []
    rooms.each do |room|
      @tourist_ids << room.tourist_id
    end
  end

# -------------- 予約ステータス変更ページ --------------



  private
  def order_params
    params.require(:order).permit(:status)
  end

  def correct_guide
    guide = Guide.find(params[:guide_id])
    if current_guide != guide
      redirect_to tour_guide_guide_path(current_guide)
    end
  end
end

app/controllers/tour_guide/rooms_controller.rb
class TourGuide::RoomsController < ApplicationController

  before_action :authenticate_guide!
  before_action :correct_guide, only: [:show, :index, :create]


  def index
    @rooms = current_guide.rooms.order(created_at: :desc).page(params[:page]).per(10)
  end


  def show
  	@room = Room.find(params[:id]) #ルーム情報の取得
    @message = Message.new #新規メッセージ投稿
    @messages = @room.messages #このルームのメッセージを全て取得
  # ------ チャット通知機能 -----
    @messages.each do |message|
      if message.is_tourist == true
        message.chat_notices.each do |chat_notice|
          chat_notice.update_attributes(checked: true)
        end
      end
    end
  # ------ チャット通知機能 -----
    if @room.guide.id == current_guide.id
    	@tourist = @room.tourist
    else
    	redirect_to root_path
    end
  end


  def create
    @room = Room.new(room_tourist_params)
    @room.guide_id = current_guide.id
    if @room.save
      redirect_to tour_guide_guide_room_path(current_guide, @room)
    else
      redirect_to tour_guide_guide_orders_path(current_guide)
    end
  end


  private
  def room_tourist_params
    params.require(:room).permit(:tourist_id)
  end


  def correct_guide
    guide = Guide.find(params[:guide_id])
    if current_guide != guide
      redirect_to tour_guide_guide_path(current_guide)
    end
  end







end

app/controllers/tour_guide/tours_controller.rb
class TourGuide::ToursController < ApplicationController

  before_action :authenticate_guide!
  before_action :correct_guide, only: [:new, :create, :edit, :update, :destroy]

  def new
  	@tour = Tour.new
    @tour_photo = @tour.tour_photos.build
  end


  def create
  	@tour = Tour.new(tour_params)
  	@tour.guide_id = current_guide.id
  	if @tour.save
  	 redirect_to tour_guide_guide_tour_path(current_guide, @tour)
    else
      render 'new'
    end
  end


  def show
  	@tour = Tour.find(params[:id])
    @tour_photos = @tour.tour_photos
    @comments = @tour.comments
  end


  def index
  	@genres = Genre.all
  	if params[:genre_id]
  		@genre = Genre.find(params[:genre_id])
  		@tours = @genre.tours.order(created_at: :desc).page(params[:page]).per(9)
  	else
  		@tours = Tour.all.order(created_at: :desc).page(params[:page]).per(9)
  	end
  end

  def edit
  	@tour = Tour.find(params[:id])
  end


  def update
  	@tour = Tour.find(params[:id])
  	if@tour.update(tour_params)
  	  redirect_to tour_guide_guide_tour_path(current_guide, @tour)
    else
      render 'edit'
    end
  end


  def destroy
    @tour = Tour.find(params[:id])
    @tour.destroy
    redirect_to tour_guide_guide_path(current_guide)
  end



  private
  def tour_params
  params.require(:tour).permit(:genre_id, :city_id, :title, :body, :capacity, :time, :price,
    :contents_of_price, :meetingpoint_address, :meetingpoint_introduction, :is_active, tour_photos_attributes: [:id, :image, :tour_id, :_destroy])
  end

  def correct_guide
    guide = Guide.find(params[:guide_id])
    if current_guide != guide
      redirect_to tour_guide_guide_path(current_guide)
    end
  end

end

app/controllers/tourist/orders_controller.rb
class Tourist::OrdersController < ApplicationController

  before_action :authenticate_tourist!
  before_action :correct_tourist, only: [:new, :confirm, :create, :destroy, :index]

  def index
    @orders = current_tourist.orders
    @comment = Comment.new
  end

  def new
  	@tourist = Tourist.find_by(id: params[:tourist_id])
    @tour = Tour.find_by(id: params[:tour_id])
  	@order = Order.new
  end


  def confirm
  	@order = Order.new(order_params)
  	if @order.companion.to_i + 1 > @order.capacity
      flash[:danger] = "定員数を超えています。"
      redirect_to new_tourist_tourist_order_path(current_tourist, tour_id: @order.tour_id)
    elsif @order.companion == ""
      redirect_to new_tourist_tourist_order_path(current_tourist, tour_id: @order.tour_id)
      flash[:danger] = "0人の場合は0とご入力ください"
    end
  	@order.total_people = @order.companion.to_i + 1
  	@total_price = @order.price * @order.total_people
  end


  def create
  	@order = Order.new(order_params)
  	@order.save
  	redirect_to tourist_orders_thanks_path
  end


  def destroy
    @order = Order.find(params[:id])
    @tourist = @order.tourist
    if @order.status == "ツアー開始前"
      @order.destroy
      redirect_to tourist_tourist_path(@tourist)
    else
      redirect_to tourist_tourist_path(@tourist)
    end
  end


  def thanks
  end


  def show
  end



  private
  def order_params
      params.require(:order).permit(:tourist_id, :tour_id, :guide_id, :tour_title, :tour_body, :price, :contents_of_price, :capacity, :companion, :total_people, :tour_time, :tour_city, :admin_sales, :guide_sales, :tour_genre, :tour_price)
  end

  def correct_tourist
    tourist = Tourist.find(params[:tourist_id])
    if current_tourist != tourist
      redirect_to tourist_tourist_path(current_tourist)
    end
  end



end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/tour_guide/guides_helper.rb
module TourGuide::GuidesHelper
end

app/helpers/tour_guide/home_helper.rb
module TourGuide::HomeHelper
end

app/helpers/tour_guide/messages_helper.rb
module TourGuide::MessagesHelper
end

app/helpers/tour_guide/notifications_helper.rb
module TourGuide::NotificationsHelper
end

app/helpers/tour_guide/orders_helper.rb
module TourGuide::OrdersHelper
end

app/helpers/tour_guide/rooms_helper.rb
module TourGuide::RoomsHelper
end

app/helpers/tour_guide/tours_helper.rb
module TourGuide::ToursHelper
end

app/helpers/tourist/orders_helper.rb
module Tourist::OrdersHelper
end

app/views/tour_guide/orders/_tbody.html.erb
<% if order.status == "ツアー前日" %>
	<tr class = "info">
<% elsif order.status == "ツアー当日" %>
	<tr class = "danger">
<% elsif order.status == "ツアー中" %>
	<tr class = "success">
<% end %>
		<td class = "text-center">
			<%= order.id %>
		</td>
		<td class = "text-center">
			<%= order.tour_title %>
		</td>
		<td class = "text-center">
			<%= order.tourist.family_name %> <%= order.tourist.name %>
		</td>
		<td class = "text-center">
			<% if order.tourist.sex == "男性" %>
				<i class="fas fa-mars fa-2x"></i>
			<% elsif order.tourist.sex == "女性" %>
				<i class="fas fa-venus fa-2x"></i>
			<% end %>
		</td>
		<td class = "text-center">
			<%= order.tourist.nationality %>
		</td>
		<td class = "text-center">
			<%= order.total_people %>名
		</td>

		<td class = "text-center">
			¥ <%= number_with_delimiter(order.guide_sales) %>
		</td>



	<!----- チャット機能 ----->
		<td class = "text-center">
			<% if @tourist_ids.include?(order.tourist.id) %>
			    <%= link_to "チャットへ", tour_guide_guide_room_path(current_guide, current_guide.rooms.find_by(tourist_id: order.tourist.id)), class: "btn btn-default" %>
			  <% else %>
			    <%= form_for(Room.new, url: tour_guide_guide_rooms_path(current_guide)) do |f| %>
			      <%= f.hidden_field :tourist_id, :value => order.tourist.id %>
			      <%= f.submit "チャットへ", class: "btn btn-default" %>
			    <% end %>
			<% end %>
		</td>
	<!----- チャット機能 ----->




	<!----- 注文ステータス更新欄 ----->
		<td class = "text-center">
			<% if order.status != "ツアー終了" or "レビュー済み" %>
				<%= form_for(order, url: tour_guide_guide_order_path(current_guide, order)) do |f| %>
		       		<%= f.select :status, Order.statuses.keys.to_a, data: { confirm: "本当に退会しますか?" } %>
		            <%= f.submit "更新", class: "btn btn-primary" %>
		       	<% end %>
		    <% elsif order.status == "ツアー終了" %>
		    	レビュー待ちです
		    <% else %>
		    	レビューを受けました。
		    <% end %>
		</td>
	<!----- 注文ステータス更新欄 ----->
	</tr>

app/views/tour_guide/orders/_thead.html.erb
<thead>
	<tr>
		<th class = "text-center">予約番号</th>
		<th class = "text-center">ツアータイトル</th>
		<th class = "text-center">予約者</th>
		<th class = "text-center">性別</th>
		<th class = "text-center">国籍</th>
		<th class = "text-center">参加人数</th>
		<th class = "text-center">利益</th>
		<th class = "text-center">チャットルーム</th>
		<th class = "text-center">予約ステータス更新</th>
	</tr>
</thead>

app/views/tour_guide/orders/around_touring.html.erb
<div class = "container">
	<div class = "row">
		<div class = "col-xs-12">
			<h3>
				（<span style= "color: blue">青＝ツアー前日</span>  /  <span style= "color: red">赤＝ツアー当日</span>  /  <span style= "color: green">緑＝ツアー中</span>）
			</h3>
			<table class = "table">
				<%= render 'thead' %>
				<tbody>
					<% @orders.each do |order| %>
						<% if order.status == "ツアー前日" or order.status == "ツアー当日" or order.status == "ツアー中" %>
							<%= render 'tbody', order: order %>
						<% end %>
					<% end %>
				</tbody>
			</table>
		</div>
	</div>
</div>

app/views/tour_guide/orders/finished_tour.html.erb
<div class = "container">
	<div class = "row">
		<div class = "col-xs-12">
			<h2>終了済みのツアー</h2>
			<table class = "table">
				<%= render 'thead' %>
				<tbody>
					<% @orders.each do |order| %>
						<% if order.status == "ツアー終了" or order.status == "レビュー済み" %>
							<%= render 'tbody', order: order %>
						<% end %>
					<% end %>
				</tbody>
			</table>
		</div>
	</div>
</div>

app/views/tour_guide/orders/index.html.erb
<div class = "container">
	<div class = "row">
		<h2 class = "order_status_flash_text"><%= flash[:notice] %></h2>
		<div class = "col-xs-9">
			<h2>各ページで予約ステータスを変更しましょう。</h2>
		</div>
	</div>
	<div class = "row">
		<div class = "col-xs-9">
			<div class =  "panel panel-default text-center">
				<div class="panel-heading">
					<h1 class="panel-title">各ステータスページ</h1>
				</div>
				<div class = "panel-body" >
					<h2>
						<%= link_to tour_guide_guide_new_order_path(current_guide) do %>
							<i class="far fa-calendar-alt"></i>
							ツアー開始前の予約
						<% end %>
					</h2>
				</div>
				<div class = "panel-body" >
					<h2>
						<%= link_to tour_guide_guide_around_touring_path(current_guide) do %>
							<i class="fas fa-map-marker-alt"></i>
							ツアー前日〜ツアー中
						<% end %>
					</h2>
				</div>
				<div class = "panel-body" >
					<h2>
						<%= link_to tour_guide_guide_finished_tour_path(current_guide) do %>
							<i class="far fa-calendar-check"></i>
							終了済みのツアー
						<% end %>
					</h2>
				</div>
			</div>
		</div>

	<!------ 総利益 ------>
		<div class = "col-xs-3">
			<table class = "table table-bordered">
				<tr>
					<th class = "active">
						<h3>総利益</h3>
					</th>
					<th>
						<h3>¥ <%= number_with_delimiter(@guide_total_sales) %></h3>
					</th>
				</tr>
			</table>
		</div>
	<!------ 総利益 ------>
	</div>
	<div class = "row">
		<div class = "col-xs-10">
			<h2>本日入った予約</h2>
			<table class = "table">
				<thead>
					<tr class = "active">
						<th class = "text-center">予約番号</th>
						<th class = "text-center">予約者</th>
						<th class = "text-center">参加人数</th>
						<th class = "text-center">売り上げ</th>
						<th class = "text-center">利益</th>
						<th class = "text-center">チャットへ</th>
					</tr>
				</thead>
				<tbody>
					<% @todays_orders.each do |order| %>
						<tr class = "text-center">
							<td><%= order.id %></td>
							<td><%= order.tourist.family_name %> <%= order.tourist.name %></td>
							<td><%= order.total_people %>名</td>
							<td>¥ <%= number_with_delimiter(order.price) %></td>
							<td>¥ <%= number_with_delimiter(order.guide_sales) %></td>
							<td>
								<% if @tourist_ids.include?(order.tourist.id) %>
								    <%= link_to "チャットへ", tour_guide_guide_room_path(current_guide, current_guide.rooms.find_by(tourist_id: order.tourist.id)), class: "btn btn-default" %>
								<% else %>
								    <%= form_for(Room.new, url: tour_guide_guide_rooms_path(current_guide)) do |f| %>
								      <%= f.hidden_field :tourist_id, :value => order.tourist.id %>
								      <%= f.submit "チャットへ", class: "btn btn-default" %>
								    <% end %>
								<% end %>
							</td>
						</tr>
					<% end %>
				</tbody>
			</table>
		</div>
	</div>
</div>

app/views/tour_guide/orders/new_order.html.erb
<div class = "container">
	<div class = "row">
		<div class = "col-xs-12">
			<h2>現在の予約</h2>
			<table class = "table">
				<%= render 'thead' %>
				<tbody>
					<% @orders.each do |order| %>
						<% if order.status == "ツアー開始前" %>
							<%= render 'tbody', order: order %>
						<% end %>
					<% end %>
				</tbody>
			</table>
		</div>
	</div>
</div>